//i stole this from ur example and didnt change much at all (except the username input n stuff)

import {System} from './firebase/system.js'
import { createUserWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/9.8.1/firebase-auth.js'
import {set, ref} from 'https://www.gstatic.com/firebasejs/9.8.1/firebase-database.js'

class Register {
  constructor() {
    this.system = new System(); //Initialize our Firebase

    this.bindRegister();
  }

  bindRegister() { //Bind the register button
    const register = document.getElementById('register'); //Grab the HTML form
    register.addEventListener('submit', (event) => this.handleRegister(event)); //What happens when the register button is pressed
  }

  handleRegister(e) { //handles registration
    e.preventDefault(); //prevents the default behaviour of refreshing the page

    //Grab all the inputs
    const username = document.getElementById('username').value;
    const email = document.getElementById('email').value;
    const password = document.getElementById('password').value;

    //Make sure none of them are empty
    if(username !== "" && email !== "" && password !== "") {
      createUserWithEmailAndPassword(this.system.authApp.auth, email, password)
      .then((userCredential) => {
        //ONLY happens AFTER you create the user
        const uid = userCredential.user.uid; //Unique ID generated by Google
        
        set(ref(this.system.db, `users/${uid}`), { //Writes the info to our DB
          username: username,
          inventory: null,
          equipped: null,
          coins: 0,
        })
        .then(() => {
          window.location.assign('lobby.html'); //Sends them to the lobby
        })
        .catch((error) => {
          window.alert(error);
        })
      })
      .catch((error) =>{
        //ONLY happens IF an error occurred
        window.alert(error); //Error pop message
      })
    }
  }
}

new Register();